### ISSUE TITLE
TCC calculation fails

### ISSUE THREAD

**Issue by gmesika-coti** [coti-io/coti-node#32]
In some full nodes occasionally there are StackOverflow exceptions due to calculation in clusterHelper.sortByTopologicalOrder that recursively adds all child tx to the topology map

2022-01-19 18:16:49.145 ERROR 3147 --- [MessageBroker-2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.StackOverflowError: null
        at io.coti.basenode.services.ClusterHelper.topologicalSortingHelper(ClusterHelper.java:56)
        at io.coti.basenode.services.ClusterHelper.topologicalSortingHelper(ClusterHelper.java:56)

**Comment by gmesika-coti** [comment]
Tested on testnet-staging, working as expected 
cc7d66806830ee25e5af6c6a83ad2bfc0481b81e
